site_title: "🎵 CMU 15798 F25"
home_md: "README.md"
nav:
  - "Home": "README.md"
  - "Schedule": "schedule.md"
  - "Activities": "activities/index.md"
  - "Showcase": "showcase/index.md"
  - "Piazza": "https://piazza.com/cmu/fall2025/15798"
