site_title: "🎵 CMU 15798 F25"
home_md: "README.md"
nav:
  - README.md: "Home"
  - schedule.md: "Schedule"
  - syllabus.md: "Syllabus"
  - resources.md: "Resources"
  - https://piazza.com/class: "Piazza"
style:
  nav_background: "#C41230"
  nav_title_color: "#FFFFFF"
  nav_link_color: "#FFFFFF"
