site_title: "🎵 CMU 15798 F25"
home_md: "README.md"
nav:
  - "Home": "README.md"
  - "Schedule": "schedule.md"
  - "Syllabus": "syllabus.md"
  - "Resources": "resources.md"
  - "Piazza": "https://piazza.com/cmu/fall2025/15798"
