site_title: "🎵 CMU 15798 F25"
home_md: "README.md"
nav:
  - "Home": "README.md"
  - "Schedule": "schedule.md"
  - "Activities": "activities/index.md"
  - "Syllabus": "syllabus.md"
  - "Drive": "https://drive.google.com/drive/folders/1NHGBA5EsAI_qbtvE_qUWwPInoPYwCVK7?usp=drive_link"
  - "Piazza": "https://piazza.com/cmu/fall2025/15798"
